/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const IndexLazyRouteImport = createFileRoute('/')()
const PdfIdLazyRouteImport = createFileRoute('/pdf/$id')()
const BooksIdLazyRouteImport = createFileRoute('/books/$id')()

const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const PdfIdLazyRoute = PdfIdLazyRouteImport.update({
  id: '/pdf/$id',
  path: '/pdf/$id',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/pdf.$id.lazy').then((d) => d.Route))
const BooksIdLazyRoute = BooksIdLazyRouteImport.update({
  id: '/books/$id',
  path: '/books/$id',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/books.$id.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/books/$id': typeof BooksIdLazyRoute
  '/pdf/$id': typeof PdfIdLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/books/$id': typeof BooksIdLazyRoute
  '/pdf/$id': typeof PdfIdLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/books/$id': typeof BooksIdLazyRoute
  '/pdf/$id': typeof PdfIdLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/books/$id' | '/pdf/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/books/$id' | '/pdf/$id'
  id: '__root__' | '/' | '/books/$id' | '/pdf/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  BooksIdLazyRoute: typeof BooksIdLazyRoute
  PdfIdLazyRoute: typeof PdfIdLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf/$id': {
      id: '/pdf/$id'
      path: '/pdf/$id'
      fullPath: '/pdf/$id'
      preLoaderRoute: typeof PdfIdLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$id': {
      id: '/books/$id'
      path: '/books/$id'
      fullPath: '/books/$id'
      preLoaderRoute: typeof BooksIdLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  BooksIdLazyRoute: BooksIdLazyRoute,
  PdfIdLazyRoute: PdfIdLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
